import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const source=readFileSync(new URL('../crates/gateway-api/admin-ui/src/auth-profiles.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {profileRow,profileFields,profilesFromForm,showProfileError}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const id='00000000-0000-0000-0000-000000000001';
const form=new FormData();
form.set('profiles_revision','4');form.append('profile_slot','employee');form.append('profile_slot','automation');
for(const [key,value] of Object.entries({'employee.id':'employees','employee.name':'Employees','employee.type':'entra_and_relayna_key','employee.enabled':'on','employee.audience':'api://employees','employee.required_scopes':'run, read','employee.required_roles':'invoke','employee.allowed_groups':'staff','employee.keys':id,'automation.id':'automation','automation.name':'Automation','automation.type':'relayna_key_only','automation.enabled':'on'}))form.set(key,value);
let result=profilesFromForm(form);
assert.equal(result.revision,4);assert.equal(result.profiles.length,2);
assert.deepEqual(result.profiles[0].entra.required_scopes,['run','read']);
assert.deepEqual(result.bindings,[{key_id:id,profile_id:'employees'}]);
assert.equal(result.profiles[1].entra,undefined);
assert.throws(()=>profilesFromForm(form,true),/Accessa/);
form.set('automation.keys',id);assert.throws(()=>profilesFromForm(form),/only once/);form.delete('automation.keys');
form.set('automation.id','employees');assert.throws(()=>profilesFromForm(form),/unique/);form.set('automation.id','automation');
form.set('employee.audience','');assert.throws(()=>profilesFromForm(form),/audience/);form.set('employee.audience','api://employees');
form.delete('employee.enabled');assert.equal(profilesFromForm(form).profiles[0].enabled,false);
form.set('employee.required_roles',Array(65).fill('role').join(','));assert.throws(()=>profilesFromForm(form),/at most 64/);
assert.throws(()=>profilesFromForm(new FormData()),/1–32/);
assert.match(profileFields({authentication_profiles:result}),/4/);
const hostile=profileRow({id:'<img>',name:'"<script>',entra:{audience:'<svg>'}},[]);
assert.doesNotMatch(hostile,/<img>|<script>|<svg>/);assert.match(hostile,/&lt;script&gt;/);
console.log('ok - authentication profile forms validate bindings, independent claims, Accessa restrictions, revisions and escaped values');

assert.match(profileFields({}), /panel-heading[^]*data-add-profile>Add profile/);
assert.equal((profileFields({}).match(/data-add-profile/g)||[]).length,1);
const main=readFileSync(new URL('../crates/gateway-api/admin-ui/src/main.ts',import.meta.url),'utf8');
assert.match(main, /<form class="modal-form"><div class="modal-scroll form-grid">\$\{endpointIdentityFields\(setting.access\)\}<\/div>/);

const pattern = profileRow().match(/pattern="([^"]+)"/)[1];
const browserPattern = new RegExp(`^(?:${pattern})$`, 'v');
assert.equal(browserPattern.test('employee-app_1'), true);
assert.equal(browserPattern.test('employee app'), false);
const notice = {attributes:{}, setAttribute(key,value){this.attributes[key]=value;}, focus(){this.focused=true;}, scrollIntoView(){this.scrolled=true;}};
assert.equal(showProfileError({querySelector:()=>notice}, 'Each Entra profile requires a valid audience.'),true);
assert.equal(notice.textContent,'Each Entra profile requires a valid audience.');
assert.equal(notice.attributes.role,'alert');assert.equal(notice.focused,true);assert.equal(notice.scrolled,true);
assert.equal(showProfileError({querySelector:()=>null},'error'),false);

const {syncIdentityFields,bindProfileEditor}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
function control(name,value='',type='text') {return {name,value,type,disabled:false,required:false,checked:true};}
function group(controls,extra={}) {return {hidden:false,querySelectorAll:()=>controls,querySelector:selector=>extra[selector],...extra};}
const mode=control('endpoint_entra_mode','profiles');
const endpointAudience=control('endpoint_audience','api://legacy');
const endpoint=group([endpointAudience],{'[name="endpoint_audience"]':endpointAudience});
const profileControls=[control('profile_slot','test'),control('test.id','automation'),control('test.name','Automation'),control('test.type','entra_and_relayna_key'),control('test.enabled','on','checkbox'),control('test.audience','api://employees'),control('test.required_scopes','invoke'),control('test.keys',id)];
const entraGroup=group(profileControls.slice(5,7));
const keyHint={hidden:true};
const row={querySelector:selector=>({'[data-profile-type]':profileControls[3],'[data-profile-entra]':entraGroup,'[name$=".audience"]':profileControls[5],'[data-profile-key-only]':keyHint}[selector])};
const editor={hidden:false,querySelectorAll:selector=>selector==='[data-profile-row]'?[row]:profileControls};
const root={querySelector:selector=>({'[name="endpoint_entra_mode"]':mode,'[data-endpoint-entra]':endpoint,'[data-profile-editor]':editor}[selector])};
const handlers={};bindProfileEditor({addEventListener:(event,handler)=>{handlers[event]=handler;}});
const change=target=>handlers.change({target:{matches:()=>true,closest:()=>root,...target}});
const submitted=()=>{const data=new FormData();for(const c of profileControls)if(!c.disabled&&(c.type!=='checkbox'||c.checked))data.append(c.name,c.value);return data;};
syncIdentityFields(root);
assert.equal(endpoint.hidden,true);assert.equal(endpointAudience.disabled,true);
assert.equal(editor.hidden,false);assert.equal(entraGroup.hidden,false);assert.equal(profileControls[5].required,true);
assert.equal(profilesFromForm(submitted()).profiles[0].entra.audience,'api://employees');
profileControls[3].value='relayna_key_only';change(profileControls[3]);
assert.equal(entraGroup.hidden,true);assert.equal(profileControls[5].disabled,true);assert.equal(profileControls[5].required,false);assert.equal(keyHint.hidden,false);
assert.equal(submitted().has('test.audience'),false);assert.equal(profilesFromForm(submitted()).profiles[0].entra,undefined);
profileControls[3].value='entra_and_relayna_key';change(profileControls[3]);
assert.equal(profileControls[5].value,'api://employees','switching back retains the unsaved audience');
assert.deepEqual(profilesFromForm(submitted()).profiles[0].entra.required_scopes,['invoke']);
for(const selected of ['inherit','disabled','required']) {
  mode.value=selected;change(mode);
  assert.equal(editor.hidden,true);assert.equal(profileControls.every(c=>c.disabled),true);
  assert.equal(endpoint.hidden,selected!=='required');assert.equal(endpointAudience.required,selected==='required');
  assert.equal(submitted().has('profile_slot'),false,'inactive profile drafts do not submit');
}
mode.value='profiles';change(mode);assert.equal(profileControls[1].value,'automation');assert.equal(profileControls[1].disabled,false);
assert.match(profileRow({type:'relayna_key_only'}), /data-profile-entra hidden/);
assert.match(profileRow({type:'relayna_key_only'}), /input disabled name="profile-\d+\.audience"/);
assert.match(profileRow(), /input required name="profile-\d+\.audience"/);
console.log('ok - dynamic identity modes hide and exclude inactive controls, require Entra audience only, and preserve drafts');

const {profileKeyOptions,selectedKeyIds,loadProfileKeys,refreshProfileKeys,openProfileKeyDialog}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const secondId='00000000-0000-0000-0000-000000000002';
const inventory={keys:[{id,key_prefix:'rk_employee',project_id:'project-one',service_names:['responses']},{id:secondId,key_prefix:'rk_robot',project_id:'project-two',disabled:true,service_names:['embeddings']}],projects:[{id:'project-one',name:'Research'},{id:'project-two',name:'Automation'}]};
for(const query of ['RK_EMPLOYEE',id,'research','PROJECT-ONE','responses','research employee'])assert.deepEqual(profileKeyOptions(inventory.keys,inventory.projects,query).map(k=>k.id),[id]);
assert.equal(profileKeyOptions(inventory.keys,inventory.projects,'missing').length,0);
assert.deepEqual(profileKeyOptions(inventory.keys,inventory.projects,'','project-two').map(k=>k.id),[secondId]);
assert.equal(profileKeyOptions(inventory.keys,inventory.projects,'robot')[0].status,'Disabled');
assert.deepEqual(selectedKeyIds(' ABC ,\n DEF '),['abc','def']);
assert.doesNotMatch(profileRow(),/<textarea/);
assert.doesNotMatch(profileRow(),/data-key-search|data-key-results/,'search/results belong only in the popup');
assert.match(profileRow(),/aria-haspopup="dialog"/);
const makePicker=value=>{
  const nodes={'[data-profile-keys]':{value},'[data-selected-keys]':{innerHTML:''},'[data-open-keys]':{focus(){this.focused=true;}}};
  return {isConnected:true,nodes,querySelector:selector=>nodes[selector]};
};
const firstPicker=makePicker(id),secondPicker=makePicker('');
const pickerRoot={dataset:{keyProject:''},querySelector:()=>({value:'profiles'})};
const pickerEditor={isConnected:true,closest:()=>pickerRoot,querySelectorAll:selector=>selector==='[data-profile-keys]'?[firstPicker.nodes[selector],secondPicker.nodes[selector]]:[firstPicker,secondPicker]};
await loadProfileKeys(pickerEditor,async()=>inventory);
assert.match(firstPicker.nodes['[data-selected-keys]'].innerHTML,/rk_employee.*Research/s);
const fakeNode=()=>({value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,handlers:{},addEventListener(type,fn){this.handlers[type]=fn;},focus(){this.focused=true;}});
const doc={body:{appendChild(node){node.isConnected=true;}},createElement(){const element=fakeNode();element.nodes=Object.fromEntries(['search','results-status','retry','apply','results','selection-count','draft','cancel'].map(name=>[`[data-key-${name}]`,fakeNode()]));element.querySelector=selector=>element.nodes[selector];return element;}};
let mounting;
const mountDialog=(backdrop,options)=>{mounting=options;return()=>{backdrop.isConnected=false;options.onClose();options.restoreFocus.focus();};};
const open=async(picker=secondPicker,loader=async()=>inventory)=>{const popup=openProfileKeyDialog(picker,pickerEditor,{doc,loadCatalog:loader,mountDialog});await Promise.resolve();return popup;};
const click=(popup,kind,key)=>popup.handlers.click({target:{closest:selector=>selector===`[data-dialog-${kind}-key]`?{dataset:{[kind==='add'?'dialogAddKey':'dialogRemoveKey']:key}}:null}});
let popup=await open();
assert.equal(mounting.initialFocus,'[data-key-search]');
assert.equal(mounting.restoreFocus,secondPicker.nodes['[data-open-keys]']);
assert.doesNotMatch(popup.nodes['[data-key-results]'].innerHTML,/rk_employee/,'keys assigned elsewhere are excluded');
popup.nodes['[data-key-search]'].value='robot';popup.nodes['[data-key-search]'].handlers.input();
click(popup,'add',secondId);
assert.equal(secondPicker.nodes['[data-profile-keys]'].value,'','popup edits do not change parent until Apply');
assert.equal(popup.nodes['[data-key-search]'].value,'','adding clears search');
assert.doesNotMatch(popup.nodes['[data-key-results]'].innerHTML,/rk_robot/,'selected keys leave available results');
assert.match(popup.nodes['[data-key-draft]'].innerHTML,/rk_robot/);
click(popup,'add',id);assert.doesNotMatch(popup.nodes['[data-key-draft]'].innerHTML,/rk_employee/,'duplicate guard also rejects synthetic stale actions');
popup.nodes['[data-key-cancel]'].handlers.click();
assert.equal(secondPicker.nodes['[data-profile-keys]'].value,'');
assert.equal(popup.isConnected,false);
assert.equal(secondPicker.nodes['[data-open-keys]'].focused,true);
popup=await open();assert.equal(popup.nodes['[data-key-search]'].value,'','reopen always starts with a clear query');
assert.doesNotMatch(popup.nodes['[data-key-draft]'].innerHTML,/rk_robot/,'Cancel discards popup selections');
click(popup,'add',secondId);popup.nodes['[data-key-apply]'].handlers.click();
assert.equal(secondPicker.nodes['[data-profile-keys]'].value,secondId);
assert.equal(popup.isConnected,false);
popup=await open();click(popup,'remove',secondId);
assert.equal(secondPicker.nodes['[data-profile-keys]'].value,secondId,'removal is also staged');
popup.nodes['[data-key-apply]'].handlers.click();assert.equal(secondPicker.nodes['[data-profile-keys]'].value,'');
pickerRoot.dataset.keyProject='project-one';popup=await open();
assert.doesNotMatch(popup.nodes['[data-key-results]'].innerHTML,/rk_robot/);
click(popup,'add',secondId);assert.doesNotMatch(popup.nodes['[data-key-draft]'].innerHTML,/rk_robot/);
popup.nodes['[data-key-cancel]'].handlers.click();pickerRoot.dataset.keyProject='';
let fail=true;popup=await open(firstPicker,async()=>{if(fail)throw new Error('offline');return inventory;});
assert.match(popup.nodes['[data-key-results-status]'].textContent,/Could not load/);
assert.equal(popup.nodes['[data-key-apply]'].disabled,true);
assert.equal(firstPicker.nodes['[data-profile-keys]'].value,id);
fail=false;popup.nodes['[data-key-retry]'].handlers.click();await Promise.resolve();
assert.equal(popup.nodes['[data-key-apply]'].disabled,false);
let prevented=false;popup.nodes['[data-key-search]'].handlers.keydown({key:'Enter',preventDefault(){prevented=true;}});assert.equal(prevented,true);
popup.nodes['[data-key-cancel]'].handlers.click();
const unknown='00000000-0000-0000-0000-000000000099';firstPicker.nodes['[data-profile-keys]'].value=unknown;
secondPicker.nodes['[data-profile-keys]'].value=secondId;
await loadProfileKeys(pickerEditor,async()=>({keys:[{id:secondId,key_prefix:'<script>"',project_id:'project-two'}],projects:inventory.projects}));
assert.match(firstPicker.nodes['[data-selected-keys]'].innerHTML,/Key details unavailable/);
assert.equal(firstPicker.nodes['[data-profile-keys]'].value,unknown);
assert.doesNotMatch(secondPicker.nodes['[data-selected-keys]'].innerHTML,/<script>/);
assert.match(secondPicker.nodes['[data-selected-keys]'].innerHTML,/&lt;script&gt;/);
// Closing while lookup is pending must not revive a popup or mutate the form.
let finish;popup=await open(firstPicker,()=>new Promise(resolve=>{finish=resolve;}));
popup.nodes['[data-key-cancel]'].handlers.click();finish(inventory);await Promise.resolve();
assert.equal(popup.isConnected,false);assert.equal(firstPicker.nodes['[data-profile-keys]'].value,unknown);
console.log('ok - modal key picker isolates drafts, Apply/Cancel, fresh/cleared search, available-only results, project scope, retry, escaping and late loading');
