import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("../crates/gateway-api/admin-ui/src/investigation.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ES2022, target: ts.ScriptTarget.ES2022 } }).outputText;
const { timingValue, matchTrafficRecord, requestInvestigationView, investigationUsageSnapshot } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
assert.deepEqual(investigationUsageSnapshot({request_id:'safe',endpoint_path:'/users/private@example.test',authorization:'secret',body:'private prompt'}),{request_id:'safe'});
assert.equal(timingValue({connection_reused:true,tcp_connect_us:120},"tcp_connect_us"),"Reused connection");
assert.equal(timingValue({tls:false},"tls_handshake_us"),"Not used · HTTP");
assert.equal(timingValue({dns_status:"ip_literal"},"dns_us"),"Not needed · IP address");
assert.equal(timingValue({},"response_headers_ms"),"Not recorded");
assert.equal(timingValue({response_headers_ms:0},"response_headers_ms"),"0 ms");
assert.equal(timingValue({tcp_connect_us:850},"tcp_connect_us"),"0.85 ms");
const usage={request_id:"reused",key_id:"key-a",project_id:"project-a",diagnostics:{traffic_id:"id-a"}};
const rows=[{id:"id-b",request_id:"reused",key_id:"key-a",project_id:"project-a"},{id:"id-a",request_id:"reused",key_id:"key-a",project_id:"project-a"}];
assert.equal(matchTrafficRecord(rows,usage),rows[1]);
assert.equal(matchTrafficRecord(rows,{...usage,diagnostics:{}}),null);
assert.equal(matchTrafficRecord(rows,{...usage,key_id:"another-key"}),null);
const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const helpers={esc,time:String,table:(headers,rows)=>JSON.stringify({headers,rows})};
const partial=requestInvestigationView({usage:{request_id:'<img src=x onerror=alert(1)>',status_code:200,total_tokens:0},notice:'<script>oops</script>'},helpers);
assert.ok(!partial.includes('<img'));
assert.ok(!partial.includes('<script>'));
assert.ok(partial.includes('Not recorded'));
assert.ok(partial.includes('Raw diagnostics &amp; hashes') || partial.includes('Raw diagnostics & hashes'));
const denied=requestInvestigationView({traffic:{request_id:'denied',attempts:0,completed:true,client_status:401,diagnostics:{failure_code:'invalid_virtual_key'},timeline:[],upstream_timings:[]}},helpers);
assert.ok(denied.includes('No upstream connection was attempted.'));
assert.ok(denied.includes('could not be authenticated'));
const interrupted=requestInvestigationView({traffic:{request_id:'stream',completed:true,streaming:true,client_status:200,diagnostics:{failure_code:'upstream_connection_closed',outcome:'stream_interrupted'},timeline:[],upstream_timings:[],recording_failures:['usage_events']}},helpers);
assert.ok(interrupted.includes('>Failed<'), 'a stream can fail after HTTP 200');
assert.ok(interrupted.includes('Recording gaps: usage_events'));
console.log('ok - shared investigation distinguishes missing/reused timings, exact correlation, stream failure and escaped metadata');
