import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const source=readFileSync(new URL('../crates/gateway-api/admin-ui/src/auth-profiles.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const {profileRow,profileFields,profilesFromForm,showProfileError}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const id='00000000-0000-0000-0000-000000000001';
const form=new FormData();
form.set('profiles_revision','4');form.append('profile_slot','employee');form.append('profile_slot','automation');
for(const [key,value] of Object.entries({'employee.id':'employees','employee.name':'Employees','employee.type':'entra_and_relayna_key','employee.enabled':'on','employee.audience':'api://employees','employee.required_scopes':'run, read','employee.required_roles':'invoke','employee.allowed_groups':'staff','employee.keys':id,'automation.id':'automation','automation.name':'Automation','automation.type':'relayna_key_only','automation.enabled':'on'}))form.set(key,value);
let result=profilesFromForm(form);
assert.equal(result.revision,4);assert.equal(result.profiles.length,2);
assert.deepEqual(result.profiles[0].entra.required_scopes,['run','read']);
assert.deepEqual(result.bindings,[{key_id:id,profile_id:'employees'}]);
assert.equal(result.profiles[1].entra,undefined);
assert.throws(()=>profilesFromForm(form,true),/Accessa/);
form.set('automation.keys',id);assert.throws(()=>profilesFromForm(form),/only once/);form.delete('automation.keys');
form.set('automation.id','employees');assert.throws(()=>profilesFromForm(form),/unique/);form.set('automation.id','automation');
form.set('employee.audience','');assert.throws(()=>profilesFromForm(form),/audience/);form.set('employee.audience','api://employees');
form.delete('employee.enabled');assert.equal(profilesFromForm(form).profiles[0].enabled,false);
form.set('employee.required_roles',Array(65).fill('role').join(','));assert.throws(()=>profilesFromForm(form),/at most 64/);
assert.throws(()=>profilesFromForm(new FormData()),/1–32/);
assert.match(profileFields({authentication_profiles:result}),/4/);
const hostile=profileRow({id:'<img>',name:'"<script>',entra:{audience:'<svg>'}},[]);
assert.doesNotMatch(hostile,/<img>|<script>|<svg>/);assert.match(hostile,/&lt;script&gt;/);
console.log('ok - authentication profile forms validate bindings, independent claims, Accessa restrictions, revisions and escaped values');

assert.match(profileFields({}), /panel-heading[^]*data-add-profile>Add profile/);
assert.equal((profileFields({}).match(/data-add-profile/g)||[]).length,1);
const main=readFileSync(new URL('../crates/gateway-api/admin-ui/src/main.ts',import.meta.url),'utf8');
assert.match(main, /<form class="modal-form"><div class="modal-scroll form-grid">\$\{endpointIdentityFields\(setting.access\)\}<\/div>/);

const pattern = profileRow().match(/pattern="([^"]+)"/)[1];
const browserPattern = new RegExp(`^(?:${pattern})$`, 'v');
assert.equal(browserPattern.test('employee-app_1'), true);
assert.equal(browserPattern.test('employee app'), false);
const notice = {attributes:{}, setAttribute(key,value){this.attributes[key]=value;}, focus(){this.focused=true;}, scrollIntoView(){this.scrolled=true;}};
assert.equal(showProfileError({querySelector:()=>notice}, 'Each Entra profile requires a valid audience.'),true);
assert.equal(notice.textContent,'Each Entra profile requires a valid audience.');
assert.equal(notice.attributes.role,'alert');assert.equal(notice.focused,true);assert.equal(notice.scrolled,true);
assert.equal(showProfileError({querySelector:()=>null},'error'),false);
