// Reviewed explanations of existing behavior. Context matters: a policy's zero
// limit differs from a filter's zero minimum or a health counter's zero count.
const layerLimit = " Blank adds no limit at this policy layer; inherited limits still apply.";
const policy: Record<string, string> = {
  allowed_routes: "Comma-separated gateway routes allowed by this layer. Blank adds no route restriction; other layers still apply.",
  allowed_models: "Comma-separated exact model names. Blank adds no model restriction; other layers still apply.",
  rpm_limit: "Requests per minute. 0 blocks requests." + layerLimit,
  tpm_limit: "Estimated tokens per minute. 0 leaves no allowance for requests with estimated tokens." + layerLimit,
  daily_budget_usd: "Daily spending ceiling in USD. Reaching the ceiling blocks requests; 0 blocks immediately." + layerLimit,
  monthly_budget_usd: "Monthly spending ceiling in USD. Reaching the ceiling blocks requests; 0 blocks immediately." + layerLimit,
  max_requests_per_day: "Maximum requests per UTC day. 0 blocks requests." + layerLimit,
  max_tokens_per_day: "Daily recorded token threshold. Reaching it blocks subsequent requests; 0 blocks immediately." + layerLimit,
  max_cost_per_request: "Maximum estimated USD cost per request. 0 allows only zero-cost estimates." + layerLimit,
  max_input_tokens_per_request: "Maximum input tokens per request. 0 allows no positive token count." + layerLimit,
  max_output_tokens_per_request: "Maximum output tokens per request. 0 allows no positive token count." + layerLimit,
  max_request_body_bytes: "Request size ceiling in bytes. 0 allows no nonempty request body." + layerLimit,
  max_response_body_bytes: "Response size ceiling in bytes. 0 allows no nonempty response body." + layerLimit,
  allowed_hours_utc: "Comma-separated UTC hours, 0–23. 0 means midnight–01:00 UTC, not disabled. Blank adds no time restriction.",
  unused_key_auto_disable_after_days: "Disable keys after this many inactive days when the maintenance check runs. 0 makes them immediately eligible; blank adds no inactivity rule.",
  allow_streaming: "Permit streamed responses at this layer. Other policy layers can still deny streaming.",
  allow_tools: "Permit tool/function calling at this layer. Other policy layers can still deny it.",
};
const shared: Record<string, string> = {
  preset: "Starting policy template. Review the resulting permissions and limits before creating the key.",
  expires_at: "Local date and time when the key stops authenticating. Use No expiration to create a key without an expiry.",
  rotation_due_at: "Optional local date and time for a rotation reminder. This does not rotate or revoke the key automatically.",
  no_expires_at: "Remove the expiry date. The key remains valid until disabled or revoked.",
  disabled: "Temporarily reject this key's requests without revoking it.",
  kind: "Policy layer to configure. Effective access combines applicable layers and keeps the stricter limits.",
  scope_id: "Identifier for the selected layer: project UUID, team ID, route or model. Global has no scope ID.",
  owner_type: "Project keys belong to a project. Individual keys are limited to their selected registered services.",
  team_id: "Optional exact team identifier to include when resolving the simulated policy.",
  path: "Gateway request path to simulate. The simulation evaluates policy without sending an upstream request.",
  request_body_bytes: "Simulated request body size in bytes. 0 means empty; blank omits this measurement.",
  response_body_bytes: "Simulated response body size in bytes. 0 means empty; blank omits this measurement.",
  stream: "Evaluate the request as streaming. This does not start a stream.",
  tools: "Evaluate the request as using tool/function calls.",
  credential_header_mode: "authorization_bearer sends Authorization: Bearer. custom_header sends the credential using the header below.",
  credential_header_name: "Header name used in custom_header mode, such as x-litellm-api-key. Ignored in authorization_bearer mode.",
  credential_header_value_format: "In custom_header mode, raw sends the secret as-is; bearer prefixes it with Bearer.",
  credential: "Write-only upstream credential. On edits, leave blank to keep the saved value; use the clear action if available to remove it.",
  scope: "Choose whether this LiteLLM credential mapping applies to one gateway key or one project.",
  key_target_id: "Gateway virtual key that will use this LiteLLM credential.",
  project_target_id: "Project whose requests will use this LiteLLM credential mapping.",
  allowed_paths: "Comma-separated path patterns eligible for wildcard forwarding, such as /v1/*. Administrative exposure is controlled separately.",
  allowed_methods: "HTTP methods the service or passthrough route accepts. Review them before enabling access.",
  timeout_ms: "Upstream timeout in milliseconds. 1,000 ms equals 1 second; 0 is not a valid timeout.",
  max_request_body_bytes: "Maximum forwarded request size in bytes. 1,048,576 bytes equals 1 MiB. Must be greater than 0.",
  max_response_body_bytes: "Maximum forwarded response size in bytes. 1,048,576 bytes equals 1 MiB. Must be greater than 0.",
  max_body_bytes: "Service request body limit in bytes. 2,097,152 bytes equals 2 MiB. Must be greater than 0.",
  ui_exposure: "Controls access to LiteLLM's UI through the gateway. Keep disabled unless this administrative access is intended.",
  admin_api_exposure: "Controls forwarding to LiteLLM administrative APIs. Enabling exposure grants access beyond model inference.",
  mode: "managed_by_gateway applies gateway routing. direct_litellm_passthrough forwards through the configured LiteLLM passthrough mode.",
  route_pattern: "Public gateway path for this service, such as /services/search/*. It must identify the intended registered route.",
  upstream_base_url: "Base URL of the upstream service, including http:// or https://. Do not include credentials in the URL.",
  health_check_path: "Relative upstream path for health checks, such as /health. Leave blank to omit the active health-check endpoint.",
  health_check_method: "HTTP method used to check the upstream health endpoint.",
  fallback_services: "Comma-separated registered service names, in fallback order, used for eligible upstream failures.",
  cost_mode: "none records no charge; fixed uses the configured USD estimate; passthrough uses upstream-reported cost when available.",
  estimated_cost_usd: "Estimated USD charge per request in fixed mode. 0 means no estimated charge. Review the selected cost mode.",
  json_pointer: "JSON Pointer into the request, such as /model or /payload/page_count, used to match this pricing rule.",
  equals: "Text value the selected request field must match for this pricing rule to apply.",
  openapi_source_path: "Relative path of the service's OpenAPI document, usually /openapi.json. Preview before syncing endpoint prices.",
  studio_service_id: "Studio's service identifier used to link this registration to its source catalog.",
  sync_status: "Recorded relationship to the Studio catalog. Changing this status does not fetch or import the service.",
  clear_credential: "Remove the saved upstream credential when saving this service.",
  token: "Write-only Studio bearer token. Leave blank to preserve a configured token; use Clear token to remove it.",
  relayna_key_header: "Header clients can use to send their Relayna virtual key, for example X-Relayna-Key.",
  apigee_trusted_header_enabled: "Trust Apigee identity headers only behind the configured trusted ingress. A shared secret is required.",
  apigee_trusted_header_secret: "Write-only shared secret for trusted Apigee headers. Leave blank to preserve it; required when enabling trusted headers.",
  entra_enabled: "Enable Entra ID token authentication using the issuer, audience and authorization settings below.",
  tenant_id: "Entra tenant UUID. This identifies the organization issuing the identity tokens.",
  audience: "Expected token audience for this gateway's application registration. It must match the token's aud claim.",
  issuer: "Trusted token issuer URL. It must match the token's iss claim.",
  oidc_discovery_url: "OpenID Connect discovery document URL used to locate issuer metadata and signing keys.",
  required_scope: "Delegated permission required in the token's scp claim, such as gateway.invoke.",
  required_role: "Application role required in the token's roles claim. It must match the role granted to the caller.",
  allowed_groups: "Comma-separated Entra group IDs used for group authorization. Use IDs, not display names.",
  accepted_algorithms: "Comma-separated accepted JWT signing algorithms, for example RS256. These must match your identity provider.",
  jwks_cache_ttl_seconds: "Signing-key cache lifetime in seconds. 300 means five minutes; must be greater than 0.",
  clock_skew_seconds: "Allowed token clock difference in seconds. 0 gives no tolerance; 60 allows one minute.",
  circuit_state: "closed permits normal routing; open blocks use; half_open allows recovery checks. This edits recorded health state.",
  active_check_ok: "Result of an active health probe. Unknown means no result, not failure. Saving does not run a probe.",
  passive_success_count: "Recorded successful upstream observations. 0 means none recorded in this state.",
  passive_failure_count: "Recorded failed upstream observations. 0 means none recorded in this state.",
  consecutive_failures: "Failures in sequence for this health state. 0 means no current failure streak.",
  average_latency_ms: "Recorded average latency in milliseconds. Blank means unknown; 0 is a measured zero.",
  last_error_code: "Optional last recorded error code for this provider health state.",
  cooldown_until: "Optional local time until which the provider remains in its configured cooldown.",
  description: "Explain what this guardrail checks so operators can decide where to apply it.",
  failure_policy: "fail_closed blocks on guardrail failure; fail_open continues; dry_run records the outcome without enforcing it.",
  endpoint_url: "HTTP endpoint that executes this guardrail. Its credential is configured separately below.",
  bearer_token: "Write-only guardrail bearer token. Leave blank on edit to keep it; Clear token removes it.",
  clear_token: "Remove the saved guardrail token when saving. This may affect guardrails that require authentication.",
  default_on: "Include this guardrail by default where its mode and policy allow it.",
  config_schema: "JSON schema describing valid per-key configuration overrides. Enter a JSON object.",
  guardrail_override_names: "Enable a configuration override for this key. Unchecking removes this override when the key policy is saved.",
  runtime_config: "JSON object used when executing this guardrail. Check its schema and avoid embedding secrets.",
  display_name: "Human-readable name for this workload identity binding.",
  client_id: "Entra application/client UUID of the workload allowed to use this binding.",
  object_id: "Optional exact service-principal object UUID. Blank matches by the other configured identity constraints.",
  role: "Membership role for this resource. Both viewer and owner can read its monitoring data; global administration requires admin access.",
  action: "Exact audit action to find. Leave blank for all actions.",
  target_type: "Exact audited resource type, such as key or provider. Leave blank for all types.",
  target_id: "Exact audited resource ID. Leave blank to include all resources.",
  actor_token_id: "Exact operator token ID, not its secret value. Leave blank for all token actors.",
  actor_member_id: "Exact member UUID whose audit activity to include. Leave blank for all members.",
  time_preset: "Time window for Usage queries. Choose Custom to use From and To; exports can override these dates.",
  interval: "Size of each timeseries bucket: hour or day. This does not change the selected time range.",
  min_cost_usd: "Minimum estimated request cost in USD. 0 includes zero-cost records; blank adds no cost filter.",
  breakdown_limit: "Maximum number of groups shown in each breakdown, not the number of request rows.",
  sort_by: "Metric used to order the top breakdown groups.",
  limit: "Maximum rows returned per page. This is a row count, not a duration or cost.",
  trace_id: "Exact trace ID linking related activity. Leave blank to include all traces.",
  task_id: "Exact task ID attached to usage records. Leave blank to include all tasks.",
  run_id: "Exact execution run ID attached to usage records. Leave blank to include all runs.",
  route: "Exact gateway route filter, such as /v1/chat/completions. Leave blank for all routes.",
  endpoint: "Exact endpoint template, such as /jobs/{job_id}, rather than a concrete URL. Leave blank for all endpoints.",
  method: "HTTP request method to include. All includes every method.",
  status_code: "Client HTTP response status to match, such as 200 or 503. Leave blank for all codes.",
  failure_code: "Exact gateway failure code to match. Leave blank to include every reason.",
};
const filterText: Record<string, string> = {
  project_id: "Project UUID to match. Blank or All includes all projects available in this workspace.",
  key_id: "Gateway key UUID to match, not a key secret or prefix. Blank or All includes all keys in scope.",
  service: "Exact registered service name. Blank or All includes every service in scope.",
  provider: "Provider recorded on the request. All includes every provider in scope.",
  model: "Exact recorded model name. Blank includes all models.",
  status: "Recorded request outcome. Failure can include an interrupted stream even if HTTP headers reported 200.",
  from: "Start time in your local timezone. Usage Custom uses this lower bound; leave blank for no lower bound.",
  to: "End time in your local timezone. Usage Custom includes records before this time; blank gives no upper bound.",
};

export function fieldGuidance(name: string, context: string): string | undefined {
  if (context === "owner") {
    if (name === "owner-range-select") return "Time window for this resource's dashboard and request logs.";
    if (name === "owner-outcome-select") return filterText.status;
    if (name === "owner-status-select") return shared.status_code;
  }
  if (context === "policy" && policy[name]) return policy[name];
  if (context === "traffic") {
    const traffic: Record<string, string> = {
      request_id: "Client correlation ID. Live mode matches contained text; saved history matches the exact ID. Blank includes all requests.",
      status: "Client HTTP status, such as 503. A 200 can still be an interrupted stream; inspect its outcome.",
      outcome: "Failures selects recorded failure reasons. Active means unfinished requests and is available only in live mode.",
      from: "Saved-history start in local time. Blank defaults to the last 24 hours. Ignored in live mode.",
      to: "Saved-history end in local time, including this instant. Blank has no upper bound. Ignored in live mode.",
    };
    if (traffic[name]) return traffic[name];
  }
  if (["usage", "traffic", "owner"].includes(context) && filterText[name]) return filterText[name];
  if (name === "request_id") return "Client request ID used for legacy debug lookup. Reused client IDs may identify a later snapshot; prefer Usage or Traffic investigation for exact correlation.";
  if (name === "base_url") return context === "studio" ? "Relayna Studio base URL, including http:// or https://. Connection settings do not import services until you run an import." : "Provider base URL, including http:// or https://. Keep credentials in the separate credential field.";
  if (name === "name") return context === "pricing" ? "Name identifying this pricing rule in recorded usage." : context === "service" ? "Unique service name: lowercase letters, numbers and hyphens, starting and ending with a letter or number." : context === "health" ? "Exact configured provider name whose recorded health state is being edited." : "Name used to identify this resource in the gateway inventory.";
  if (name === "enabled") return context === "passthrough" ? "Enable wildcard forwarding only for the allowed paths and methods below." : "Allow this configuration to be used. Turning it off preserves the saved configuration.";
  if (name === "provider") return "Provider adapter used for this configuration or simulated request.";
  if (name === "model") return "Exact model name to evaluate in the simulated request.";
  if (name === "status") return context === "health" ? "Recorded health classification. Saving updates this state; use Run checks to obtain fresh probe results." : undefined;
  if (name === "project_id") return "Project that owns this key or receives this identity's exact access binding.";
  if (name === "service_name") return "Exact registered service for this request or access binding.";
  if (name === "key_id") return "Key whose effective policy to simulate. Default policy evaluates without selecting a stored key.";
  if (name !== "guardrail_override_names" && name.startsWith("guardrail_override_")) return "JSON object overriding this guardrail's configuration for this key. It must match the guardrail's config schema.";
  return shared[name];
}

export const termGuidance: Record<string, string> = {
  "Routing mode": "Mode recorded for this request. LiteLLM passthrough forwards without gateway token/cost metering. Gateway managed uses the gateway request path. Not recorded means the mode was not captured or routing was unresolved; it does not infer today’s settings.",
  "Requests": "Number of recorded requests in the selected scope and time range. It is not the count of all requests ever received.",
  "Failures": "Recorded failed requests, including failures after streaming headers. It may differ from the count of non-200 HTTP statuses.",
  "Error rate": "Recorded failed requests divided by recorded requests in the selected scope and time range.",
  "Fallbacks": "Recorded fallback routing activity in the selected scope and sample. Inspect requests to see individual attempts.",
  "Expensive": "Requests with estimated cost of at least USD 1, or the selected Minimum cost threshold when provided.",
  "Guardrail blocks": "Requests recorded as blocked by a guardrail in the selected scope and time range.",
  "Cost mode": "none records no charge; fixed uses a configured USD estimate; passthrough uses upstream-reported cost when available.",
  "Success rate": "Successful recorded requests divided by all recorded requests in the selected scope and time range.",
  "Failure rate": "Failed recorded requests divided by all recorded requests in the selected scope and time range. Missing samples are not zero failures.",
  "Fallback rate": "Share of recorded requests that used fallback routing in the selected scope and time range.",
  "Estimated cost": "Estimated usage cost in USD, based on the recorded pricing source. This is not a provider invoice.",
  "Cost": "Estimated usage cost in USD for the selected records, not a provider invoice.",
  "Average latency": "Average recorded request duration in milliseconds for the selected scope and time range.",
  "Avg latency": "Average recorded request duration in milliseconds for this group.",
  "Latency": "Recorded request duration in milliseconds. It can include response streaming and downstream delivery.",
  "Tokens": "Recorded input and output token usage. Not metered by gateway identifies LiteLLM passthrough. Not recorded means missing data; neither means zero tokens.",
  "Client HTTP": "HTTP status confirmed for the downstream client. A streamed 200 may still end in failure; check the request outcome.",
  "Upstream HTTP": "HTTP status returned by the upstream provider. No status may mean no response headers were received.",
  "Attempts": "Number of upstream selections, including eligible retries or fallbacks. 0 means no upstream was selected.",
  "Upstream attempts": "Number of upstream selections, including retries or fallbacks. 0 means no upstream was selected.",
  "Total duration": "Gateway-observed elapsed request duration, including response delivery. It is not client-render time.",
  "DNS resolution": "Hostname resolution time, including the OS resolver/cache. IP literals need no DNS; missing data is not a measured zero.",
  "Elapsed": "Milliseconds since the gateway received the request. 0 marks the start or an event within the first millisecond.",
  "Attempt": "Upstream attempt number. 0 is gateway processing before the first upstream attempt; 1 is the first attempt.",
  "Trace ID": "Distributed tracing identifier, when recorded. Use it to correlate gateway activity with other instrumented services.",
  "Task / run": "Relayna task and execution run identifiers recorded with this request. Not recorded means the request supplied no retained linkage.",
  "Gateway instance": "Gateway process that observed this request. Live Traffic is limited to one instance; saved history spans instances.",
  "Service version": "Version reported by the upstream service and retained by the gateway. Not recorded does not identify a deployment version.",
  "DNS": "Hostname resolution time, including the OS resolver/cache. IP literals need no DNS; missing data is not a measured zero.",
  "TCP connect": "New TCP connection setup, excluding DNS and TLS. A reused connection has no new connect measurement.",
  "TLS handshake": "New TLS handshake after TCP connects. Reused connections have no new handshake; plain HTTP does not use TLS.",
  "Response headers": "Time from this upstream attempt's start until response headers arrive, including connection setup.",
  "First body byte": "Time from attempt start until the first nonempty upstream body chunk, which may be a streaming keepalive.",
  "First content token": "Time to the first supported SSE content event. Keepalives and role-only events are excluded; observation is bounded.",
  "Attempt duration": "Time from attempt start until failure, retry or completion. A successful attempt includes downstream delivery.",
  "Request hash": "Fingerprint and length of request data for correlation. It is not the raw request body.",
  "Response hash": "Fingerprint and length of response data for correlation. It is not the raw response body.",
  "Circuit": "closed permits normal routing; open blocks use; half_open indicates recovery probing.",
  "Circuit state": "closed permits normal routing; open blocks use; half_open indicates recovery probing.",
  "Credential": "Whether a write-only upstream credential is configured. This never displays the saved secret.",
  "Lifecycle": "Key expiry, disable/revoke and rotation state. Rotation due is a reminder, not automatic revocation.",
  "Outcome": "Recorded completion or failure outcome, independent of whether HTTP headers were already delivered.",
  "Failure reason": "Gateway classification of the failure. Inspect the request for its source, stage and upstream evidence.",
  "Recording": "Whether diagnostic persistence encountered a problem. Missing saved evidence does not prove a request succeeded.",
  "Modes": "Guardrail execution stages: pre_call before forwarding, post_call after a response, during_call during streaming.",
  "Failure policy": "fail_closed blocks guardrail failures, fail_open continues, and dry_run records without enforcement.",
  "TTL": "Time to live: how long a cached entry remains valid before refresh or expiration.",
};
